# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml>=6"]
# ///
"""Validate cases/*.yaml and checklist.yaml, then generate every agent-facing output from them.

usage: uv run build.py           # write outputs
       uv run build.py --check   # fail if any output is out of date (CI)

Outputs:
  skills/ml-genomics-failures/SKILL.md     Agent Skill: audit procedure + case index (Claude, Codex, Cursor, ...)
  skills/ml-genomics-failures/FAILURES.md  Agent Skill: full cases, read on demand
  dist/AGENTS.md                           everything in one markdown file (Devin Knowledge, AGENTS.md, prompts)
  dist/failures.json                       machine-readable checklist + cases (MCP server, other tools)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parent
SKILL_DIR = ROOT / "skills" / "ml-genomics-failures"
REPO_URL = "https://github.com/genesjpgorg/ml-genomics-failures"

CASE_FIELDS = {
    "id": str,
    "title": str,
    "domain": str,
    "classes": list,
    "claim": str,
    "mechanism": str,
    "red_flags": list,
    "test": str,
    "fix": str,
    "sources": list,
    "status": dict,
}
STATES = ("published", "internal")
GENERATED = "<!-- Generated by build.py from cases/*.yaml and checklist.yaml. Do not edit by hand. -->"


# --- load and validate --------------------------------------------------------------------------------------


def load() -> tuple[dict, list[dict]]:
    checklist = yaml.safe_load((ROOT / "checklist.yaml").read_text())
    codes = {c["code"] for c in checklist["classes"]}
    cases, errors = [], []
    for path in sorted((ROOT / "cases").glob("*.yaml")):
        case = yaml.safe_load(path.read_text())
        errors += [f"{path.name}: {e}" for e in validate(case, path.stem, codes)]
        cases.append(case)
    ids = [c.get("id") for c in cases]
    errors += [f"duplicate id {i}" for i in sorted({i for i in ids if ids.count(i) > 1})]
    if errors:
        sys.exit("invalid cases:\n  " + "\n  ".join(errors))
    for c in cases:  # YAML reads 2026-10-04 as a date
        if "date" in c["status"]:
            c["status"]["date"] = str(c["status"]["date"])
    return checklist, cases


def validate(case: dict, stem: str, codes: set[str]) -> list[str]:
    errors = []
    for field, kind in CASE_FIELDS.items():
        if not isinstance(case.get(field), kind) or not case[field]:
            errors.append(f"'{field}' missing, empty or not a {kind.__name__}")
    if errors:
        return errors
    if case["id"] != stem:
        errors.append(f"id {case['id']} doesn't match file name {stem}")
    errors += [f"unknown class {c}" for c in case["classes"] if c not in codes]
    errors += [
        f"source {i} needs a 'citation'" for i, s in enumerate(case["sources"]) if not s.get("citation")
    ]
    status = case["status"]
    if status.get("state") not in STATES:
        errors.append(f"status.state must be one of {STATES}")
    if status.get("state") == "internal" and not (status.get("date") and status.get("pending")):
        errors.append("internal cases need status.date and status.pending")
    extra = set(case) - set(CASE_FIELDS)
    if extra:
        errors.append(f"unknown fields {sorted(extra)}")
    return errors


# --- render -------------------------------------------------------------------------------------------------


def classes_table(checklist: dict) -> str:
    rows = [f"| **{c['code']}** | {c['name']} | {c['test']} |" for c in checklist["classes"]]
    return "\n".join(["| Code | Class | One-line test |", "|---|---|---|", *rows])


def audit_section(checklist: dict, level: int) -> str:
    h = "#" * level
    steps = [
        f"{i}. **{s['title']}{'' if s['title'][-1] in '.?!' else '.'}** {s['text']}" for i, s in enumerate(checklist["audit"]["steps"], 1)
    ]
    usage = [f"- {u}" for u in checklist["usage"]]
    return "\n".join(
        [
            f"{h} Pitfall classes",
            "",
            classes_table(checklist),
            "",
            f"{h} Audit procedure",
            "",
            checklist["audit"]["intro"],
            "",
            *steps,
            "",
            f"{h} How to use the cases",
            "",
            *usage,
        ]
    )


def index_table(cases: list[dict]) -> str:
    rows = [
        f"| {c['id']} | {c['title']} | {', '.join(c['classes'])} | {c['status']['state']} |"
        for c in cases
    ]
    return "\n".join(["| ID | Case | Class | Status |", "|---|---|---|---|", *rows])


def status_text(s: dict) -> str:
    if s["state"] == "internal":
        return f"internal ({s['date']}). Pending: {s['pending']}"
    return s["state"]


def render_case(c: dict, level: int) -> str:
    sources = [f"  - {s['citation']}" + (f" {s['url']}" if s.get("url") else "") for s in c["sources"]]
    flags = [f"  - {f}" for f in c["red_flags"]]
    return "\n".join(
        [
            f"{'#' * level} {c['id']}. {c['title']}",
            "",
            f"- **Domain:** {c['domain']}",
            f"- **Class:** {', '.join(c['classes'])}",
            f"- **Claim:** {c['claim']}",
            f"- **What went wrong:** {c['mechanism']}",
            "- **Red flags:**",
            *flags,
            f"- **Test that exposes it:** {c['test']}",
            f"- **Fix:** {c['fix']}",
            "- **Sources:**",
            *sources,
            f"- **Status:** {status_text(c['status'])}",
        ]
    )


def skill_md(checklist: dict, cases: list[dict]) -> str:
    return "\n".join(
        [
            "---",
            f"name: {checklist['name']}",
            f"description: {json.dumps(checklist['description'], ensure_ascii=False)}",
            "---",
            "",
            GENERATED,
            "",
            f"# {checklist['title']}",
            "",
            checklist["summary"] + " The cases are in `FAILURES.md`, next to this file.",
            "",
            audit_section(checklist, 2),
            "",
            "## Cases",
            "",
            index_table(cases),
            "",
            "Read the matching entries in `FAILURES.md` before citing a case.",
            "",
            "## Adding a case",
            "",
            f"Cases live as YAML in {REPO_URL} (`cases/`). Add one there and run `uv run build.py`; don't edit these "
            "generated files.",
            "",
        ]
    )


def failures_md(checklist: dict, cases: list[dict]) -> str:
    codes = ", ".join(f"**{c['code']}** {c['name'].lower()}" for c in checklist["classes"])
    return "\n\n".join(
        [
            GENERATED,
            f"# {checklist['title']} (cases)",
            f"Class codes: {codes}. See `SKILL.md` for the audit procedure.",
            index_table(cases),
            *[render_case(c, 2) for c in cases],
        ]
    ) + "\n"


def agents_md(checklist: dict, cases: list[dict]) -> str:
    return "\n\n".join(
        [
            GENERATED,
            f"# {checklist['title']}",
            checklist["summary"],
            f"Use this when: {checklist['description']}",
            audit_section(checklist, 2),
            "## Cases",
            index_table(cases),
            *[render_case(c, 3) for c in cases],
            f"Source: {REPO_URL}",
        ]
    ) + "\n"


def failures_json(checklist: dict, cases: list[dict]) -> str:
    return json.dumps({"checklist": checklist, "cases": cases}, indent=2, ensure_ascii=False) + "\n"


# --- main ---------------------------------------------------------------------------------------------------


def main() -> None:
    check = "--check" in sys.argv[1:]
    checklist, cases = load()
    outputs = {
        SKILL_DIR / "SKILL.md": skill_md(checklist, cases),
        SKILL_DIR / "FAILURES.md": failures_md(checklist, cases),
        ROOT / "dist" / "AGENTS.md": agents_md(checklist, cases),
        ROOT / "dist" / "failures.json": failures_json(checklist, cases),
    }
    stale = []
    for path, text in outputs.items():
        rel = path.relative_to(ROOT)
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(rel))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {rel}")
    if stale:
        sys.exit(f"out of date (run `uv run build.py`): {', '.join(stale)}")
    print(f"{len(cases)} cases OK")


if __name__ == "__main__":
    main()
